### ISSUE TITLE
Page Update for Speakers

### ISSUE THREAD

**Issue by oonid** [pyconid/pyconid2020#19]
Hi,

I have initiated markdown files and images for our 3 keynote speakers #18 but it still needs some guidance:

- Where the images directory for the speaker's images?

- Who can help to create their bio?

- Still need to find and update their LinkedIn page.

- Waiting for the update on the main page that would refer to the speaker's page.

any thoughts?
thank you.

**Comment by adifdwimaulana** [comment]
Now, you can doing pull request for speaker details. Please read the contributing guidelines at https://github.com/pyconid/pyconid2020/blob/master/contributing.md on add/update speaker section
