### ISSUE TITLE
Menambahkan README di repo

### ISSUE THREAD

**Issue by oonid** [pyconid/pyconid2020#2]
halo,
dengan mulai aktifnya development di repo ini,
perlu ditambahkan README.
termasuk salah satunya kalo orang mau ikut berkontribusi, cara menggunakannya seperti apa?
terima kasih.

**Comment by aldamr01** [comment]
Untuk README, sudah ditambahkan di branch development, serta saya tambahkan Contributing.md untuk petunjuk / informasi apabila ingin ikut berkontribusi. Terimakasih :) 

Oh iya, mungkin apabila ada saran / masukan / tambahan pada README / Contributing.md agar kelihatan lengkap dokumentasinya, bisa langsung mas tambahkan di readme / contributing nya mas :)
